---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: registry
  name: registry
  namespace: registry
spec:
  containers:
  - image: registry:latest
    name: registry
    ports:
    - containerPort: 5000
    resources: {}
  hostNetwork: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
