---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - image: rayshoo/ubuntu
    name: ubuntu
    command: ["dd"]
    args:
    - if=/dev/zero
    - of=/dev/null
    resources: {}
    volumeMounts:
      - name: data
        mountPath: /mnt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
status: {}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
