apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: registry
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/workspace/dockerfile",
            "--context=dir://workspace",
            "--destination=10.254.1.51:5000/test"] # replace with your dockerhub account
    volumeMounts:
      - name: dockerfile-storage
        mountPath: /workspace
  volumes:
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
