apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 10.254.1.2-10.254.1.49
        - 10.254.1.60-10.254.1.254
